server:
  port: 20000

spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/fintech
    #    url: jdbc:mysql://mysql-container:3306/mydb
    url: jdbc:mysql://localhost:3306/mydb
    username: mydb
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.h2.Driver

  jpa:
    #    open-in-view : false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
