spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/fintech
    #    url: jdbc:mysql://mysql-container:3306/mydb
    url: jdbc:mysql://localhost:3306/mydb
    username: mydb
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.h2.Driver

  jpa:
    #    open-in-view : false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace